### ISSUE TITLE
Use disposition codes in offense section

### ISSUE THREAD

**Issue by georgehelman** [deardurham/ciprs-reader#10]
The DEAR team uses disposition codes to fill in the disposition column in the offense section. Update petition generator to use these codes.
[ACIS codes.pdf](https://github.com/deardurham/dear-petition/files/3534945/ACIS.codes.pdf)

**Comment by georgehelman** [comment]
This one may be tricky. It looks like we won't get the 1:1 mapping we were hoping for. Daniel Bowes' value of DISPOSED BY JUDGE isn't there. My best guess is code "JU". https://dear-petition.herokuapp.com/petition/view/75/ has value PROBATION OTHER, and I have no guess what that could be on the code chart. Also, https://dear-petition.herokuapp.com/petition/view/83/ has DISSMISSED BY COURT instead of DISMISSED BY THE COURT, like the code chart suggests, so a simple dict lookup may not suffice.

**Comment by copelco** [comment]
Sarah found the most common ones:

DISPOSED BY JUDGE: JU
DISMISSAL WITHOUT LEAVE BY DA: VD
DISMISSED BY COURT: DC
DEFERRED PROCEEDING OR DEFERRED PROSECUTION DISMISSAL: DD
WAIVER - CLERK: WC

**Comment by copelco** [comment]
Fixed in #12
