### ISSUE TITLE
Update date parsers to return MM/DD/YYYY format

### ISSUE THREAD

**Issue by georgehelman** [deardurham/ciprs-reader#11]
Right now date parsers return datetime strings, which get converted to MM-DD-YYYY format for display, but this results in a lot of duplicated code because it always needs to be converted to MM/DD/YYYY (``%m/%d/%Y``) format in the end. We can DRY our code by making the parser return that format in the first place.

**Comment by copelco** [comment]
Fixed in deardurham/dear-petition#39
