### ISSUE TITLE
Extract “additional offenses exist” language

### ISSUE THREAD

**Issue by copelco** [deardurham/ciprs-reader#34]
Summary records can contain the following language: 

> Additional offenses exist. To see a complete breakdown, view full case detail.

If it exists, this should be noted in the JSON so dear-petition can pick it up and display a message to the user:

```json
{
    "Additional offenses exist": "true"
}
```

**Comment by georgehelman** [comment]
@copelco Do we have a handy example of this language?

**Comment by georgehelman** [comment]
We no longer support summary records, so closing this issue.
