### ISSUE TITLE
Multi-Line Reader Mode on Mac with M1 processor

### ISSUE THREAD

**Issue by rebecca-draben** [deardurham/ciprs-reader#64]

**Comment by rebecca-draben** [comment]
When running on Mac with M1 processor, checking the Multi-Line Reader Mode during CIPRS record upload causes an error.

`ERROR 2023-03-30 10:06:25,434 dear_petition.petition.etl.extract 90 281472724955616 Command 'pdftotext-4 -enc UTF-8 -table /tmp/ciprs-m260psi3/report.pdf -' returned non-zero exit status 255.`

**Comment by robert-w-gries** [comment]
Fixed in #67
